### PR TITLE
[UTI-2480] Fix `set-output` usage

### PR DESCRIPTION
**Pull request by konstrybakov**
Hey there, I wonder if you could help me out please!

We are using the `jenkins-job-trigger-action` `v0.0.2` and it has a `set-output` usage, which will be deprecated. It turns out the `master` version also uses `set-output` so I am submitting a fix here.

We are running a small initiative for our projects where we are fixing the deprecation notices from workflows, and this action generates one.

What would be the best approach? We use the 0.0.2 version, and I see that 1.0.0 is a breaking change. I see from the code that there are some new `required` params, but is that it?

What would I do to start using a version with updated `set-output` usage?

Also, I am not sure how you version this, I see from code you do it manually, do you want me to update it also in this PR?

### CODE REVIEW

**Comment by konstrybakov** [comment]
@toptal-anvil ping reviewers

**Comment by romanrod** [comment]
@konstrybakov I'm not sure if it's possible to create an intermediate version like 0.0.3 from the commit for version 0.0.2, generate and push the proper version tag and then do the same from the current master to update and generate the latest version with the changes as well. If this works, then we should update all workflows to newer versions accordingly

**Comment by konstrybakov** [comment]
@romanrod! Hey, Roman, to be 100% honest I didn't quite catch what you are suggesting :) 

I've made a test run with the current branch and all went well. Meaning I can probably use a `1.0.1` version for this commit and update our projects with that. WDYT? 

https://github.com/toptal/img-resize.com/actions/runs/3571602493/jobs/6003645363

Screenshot 2022-11-29 at 08 32 54

**Comment by konstrybakov** [comment]
So it seems like `proxy` param is not required for a successful run

**Comment by romanrod** [comment]
@konstrybakov If a required parameter can be avoided (what is strange for me) and the execution works fine I think your suggestion is doable

**Comment by konstrybakov** [comment]
@romanrod Can you approve then maybe, please? I need this contribution to finish my task

Or if you feel something has to be changed, please let me know

**Comment by konstrybakov** [comment]
@denieler Hello, Daniel, do you by any chance know why my run finished successfully without a `proxy` param? If it's not `required` I can mark it as such in my PR as well

**Review by romanrod — DISMISSED** [review]

**Review by romanrod — APPROVED** [review]

**Pull request merged**
